codecov:
  notify:
    require_ci_to_pass: true

coverage:
  precision: 2
  round: down

  status:
    project: true
    patch: true
    changes: false

comment:
  layout: "reach,diff,flags"
  behavior: once
